// Parity gate: TypeScript engine outputs must match the Python reference to
// 1e-12 across a dense input grid. Fixture is regenerated by running
// `python tests/generate_parity_fixtures.py` from the repo root.

import { describe, it, expect } from "vitest";
import fixtures from "./parity_fixtures.json";

import {
  amplitudeDampingKraus,
  applyKrausChannel,
  depolarizingKraus,
  krausCompletenessResidual,
  phaseDampingKraus,
} from "../lib/noise";
import {
  analyticalAmplitudeDensity,
  analyticalAmplitudeFidelity,
  analyticalPhaseDensity,
  analyticalPhaseFidelity,
} from "../lib/analytical";
import { eigenvalues, fidelity, purity } from "../lib/metrics";
import {
  repetitionSuccessProtected,
  repetitionSuccessUnprotected,
} from "../lib/qec";
import { densityMatrix, ketOne, ketZero, plusState } from "../lib/states";
import { type Complex } from "../lib/complex";
import { type Mat, type Vec } from "../lib/matrix";

const TOL = 1e-12;

type FixtureMatrix = number[][][]; // [[re, im], ...]
type FixtureVector = number[][];

function fromFixtureMatrix(m: FixtureMatrix): Mat {
  return m.map((row) => row.map((entry) => ({ re: entry[0], im: entry[1] })));
}

function fromFixtureVector(v: FixtureVector): Vec {
  return v.map((entry) => ({ re: entry[0], im: entry[1] }));
}

function assertMatrixClose(sim: Mat, ref: Mat, tol = TOL): void {
  expect(sim.length).toBe(ref.length);
  for (let i = 0; i < sim.length; i++) {
    expect(sim[i].length).toBe(ref[i].length);
    for (let j = 0; j < sim[i].length; j++) {
      const s = sim[i][j];
      const r = ref[i][j];
      expect(Math.abs(s.re - r.re), `re mismatch @ [${i}][${j}]`).toBeLessThanOrEqual(tol);
      expect(Math.abs(s.im - r.im), `im mismatch @ [${i}][${j}]`).toBeLessThanOrEqual(tol);
    }
  }
}

const STATE_FACTORIES: Record<string, () => Vec> = {
  ket0: ketZero,
  ket1: ketOne,
  plus: plusState,
};

const CHANNEL_FACTORIES: Record<string, (p: number) => Mat[]> = {
  amplitude_damping: amplitudeDampingKraus,
  phase_damping: phaseDampingKraus,
  depolarizing: depolarizingKraus,
};

describe("parity: states", () => {
  for (const [name, refVec] of Object.entries(fixtures.states as Record<string, FixtureVector>)) {
    it(`ket ${name} matches Python`, () => {
      const ts = STATE_FACTORIES[name]();
      const ref = fromFixtureVector(refVec);
      expect(ts.length).toBe(ref.length);
      for (let i = 0; i < ts.length; i++) {
        expect(Math.abs(ts[i].re - ref[i].re)).toBeLessThanOrEqual(TOL);
        expect(Math.abs(ts[i].im - ref[i].im)).toBeLessThanOrEqual(TOL);
      }
    });
  }

  for (const [name, refMat] of Object.entries(fixtures.density_matrices as Record<string, FixtureMatrix>)) {
    it(`density_matrix(${name}) matches Python`, () => {
      const rho = densityMatrix(STATE_FACTORIES[name]());
      assertMatrixClose(rho, fromFixtureMatrix(refMat));
    });
  }
});

describe("parity: channels", () => {
  for (const [chName, entries] of Object.entries(fixtures.channels as Record<string, unknown[]>)) {
    const factory = CHANNEL_FACTORIES[chName];
    for (const raw of entries as Array<{
      param: number;
      kraus: FixtureMatrix[];
      completeness_residual: number;
      applied_to: Record<string, FixtureMatrix>;
    }>) {
      it(`${chName} @ param=${raw.param}: Kraus operators match`, () => {
        const tsKraus = factory(raw.param);
        expect(tsKraus.length).toBe(raw.kraus.length);
        raw.kraus.forEach((refK, idx) => {
          assertMatrixClose(tsKraus[idx], fromFixtureMatrix(refK));
        });
      });
      it(`${chName} @ param=${raw.param}: completeness residual matches`, () => {
        const ts = krausCompletenessResidual(factory(raw.param));
        expect(Math.abs(ts - raw.completeness_residual)).toBeLessThanOrEqual(1e-10);
      });
      for (const [stateName, refOut] of Object.entries(raw.applied_to)) {
        it(`${chName} @ param=${raw.param} applied to ${stateName} matches`, () => {
          const rho0 = densityMatrix(STATE_FACTORIES[stateName]());
          const out = applyKrausChannel(rho0, factory(raw.param));
          assertMatrixClose(out, fromFixtureMatrix(refOut));
        });
      }
    }
  }
});

describe("parity: fidelity vs |+>", () => {
  for (const [chName, curve] of Object.entries(fixtures.fidelity_vs_plus as Record<string, Array<{ param: number; F: number }>>)) {
    for (const point of curve) {
      it(`${chName} @ param=${point.param}: F matches`, () => {
        const rho0 = densityMatrix(plusState());
        const rho = applyKrausChannel(rho0, CHANNEL_FACTORIES[chName](point.param));
        const f = fidelity(rho, plusState());
        expect(Math.abs(f - point.F)).toBeLessThanOrEqual(TOL);
      });
    }
  }
});

describe("parity: purity curves", () => {
  for (const [chName, curve] of Object.entries(fixtures.purity_curves as Record<string, Array<{ param: number; P: number }>>)) {
    for (const point of curve) {
      it(`${chName} @ param=${point.param}: P matches`, () => {
        const rho0 = densityMatrix(plusState());
        const rho = applyKrausChannel(rho0, CHANNEL_FACTORIES[chName](point.param));
        const p = purity(rho);
        expect(Math.abs(p - point.P)).toBeLessThanOrEqual(TOL);
      });
    }
  }
});

describe("parity: eigenvalue grids", () => {
  for (const [chName, grid] of Object.entries(fixtures.eigenvalue_grids as Record<string, Array<{ param: number; eigs: number[] }>>)) {
    for (const point of grid) {
      it(`${chName} @ param=${point.param}: eigenvalues match`, () => {
        const rho0 = densityMatrix(plusState());
        const rho = applyKrausChannel(rho0, CHANNEL_FACTORIES[chName](point.param));
        const tsEigs = eigenvalues(rho);
        expect(tsEigs.length).toBe(point.eigs.length);
        for (let i = 0; i < tsEigs.length; i++) {
          expect(Math.abs(tsEigs[i] - point.eigs[i])).toBeLessThanOrEqual(TOL);
        }
      });
    }
  }
});

describe("parity: analytical formulas", () => {
  for (const entry of fixtures.analytical.rho_AD as Array<{ gamma: number; rho: FixtureMatrix }>) {
    it(`rho_AD(${entry.gamma}) matches`, () => {
      assertMatrixClose(analyticalAmplitudeDensity(entry.gamma), fromFixtureMatrix(entry.rho));
    });
  }
  for (const entry of fixtures.analytical.rho_PD as Array<{ lambda: number; rho: FixtureMatrix }>) {
    it(`rho_PD(${entry.lambda}) matches`, () => {
      assertMatrixClose(analyticalPhaseDensity(entry.lambda), fromFixtureMatrix(entry.rho));
    });
  }
  for (const entry of fixtures.analytical.F_AD as Array<{ gamma: number; F: number }>) {
    it(`F_AD(${entry.gamma}) matches`, () => {
      expect(Math.abs(analyticalAmplitudeFidelity(entry.gamma) - entry.F)).toBeLessThanOrEqual(TOL);
    });
  }
  for (const entry of fixtures.analytical.F_PD as Array<{ lambda: number; F: number }>) {
    it(`F_PD(${entry.lambda}) matches`, () => {
      expect(Math.abs(analyticalPhaseFidelity(entry.lambda) - entry.F)).toBeLessThanOrEqual(TOL);
    });
  }
});

describe("parity: QEC formulas", () => {
  for (const entry of fixtures.qec as Array<{ p: number; unprot: number; prot: number }>) {
    it(`p=${entry.p}: unprotected matches`, () => {
      expect(Math.abs(repetitionSuccessUnprotected(entry.p) - entry.unprot)).toBeLessThanOrEqual(TOL);
    });
    it(`p=${entry.p}: protected matches`, () => {
      expect(Math.abs(repetitionSuccessProtected(entry.p) - entry.prot)).toBeLessThanOrEqual(TOL);
    });
  }
});
