"""Quantum Noise Learning Lab — landing page."""

from __future__ import annotations

import streamlit as st

from app.components.explain import page_footer
from app.components.theme import inject_styles

st.set_page_config(
    page_title="Quantum Noise Learning Lab",
    page_icon="🌀",
    layout="wide",
    initial_sidebar_state="expanded",
)
inject_styles()

st.title("Quantum Noise Learning Lab")
st.markdown(
    "**An interactive educational lab for exploring how a single qubit "
    "decoheres under noise — and what we can do about it.**"
)

st.markdown(
    "> *How does quantum information degrade under noise, and how can we "
    "understand, measure, visualize, and partially protect it?*"
)

st.divider()
st.subheader("Pick a module to start")

MODULES = [
    {
        "title": "1 · Foundations Lab",
        "icon": "🧱",
        "summary": "Build single-qubit state vectors and density matrices. "
        "See why ρ — not |ψ⟩ — is the right object for noisy states.",
        "page": "pages/1_Foundations_Lab.py",
    },
    {
        "title": "2 · Noise Lab",
        "icon": "🌫️",
        "summary": "Watch amplitude damping, phase damping, and depolarizing "
        "channels deform ρ. Kraus operators in LaTeX, Δρ scalar summary.",
        "page": "pages/2_Noise_Lab.py",
    },
    {
        "title": "3 · Metrics Lab",
        "icon": "📊",
        "summary": "Quantify the deformation with fidelity, purity, and "
        "eigenvalue analysis; sweep noise to see the trajectory.",
        "page": "pages/3_Metrics_Lab.py",
    },
    {
        "title": "4 · Validation Lab",
        "icon": "✅",
        "summary": "Side-by-side check: simulated ρ against closed-form "
        "analytical formulas for |+⟩, with live |error| heatmap.",
        "page": "pages/4_Validation_Lab.py",
    },
    {
        "title": "5 · Protection Lab",
        "icon": "🛡️",
        "summary": "Classical-style 3-repetition success curves — and an "
        "honest panel on what real quantum error correction adds.",
        "page": "pages/5_Protection_Lab.py",
    },
]

cols = st.columns(len(MODULES), gap="medium")
for col, mod in zip(cols, MODULES):
    with col:
        st.markdown(f"### {mod['icon']} {mod['title']}")
        st.caption(mod["summary"])
        try:
            st.page_link(mod["page"], label="Open module →")
        except Exception:
            st.markdown(f"`{mod['page']}`")

st.divider()

col_a, col_b = st.columns([1, 1], gap="large")
with col_a:
    st.subheader("What this lab is")
    st.markdown(
        """
        - A focused single-qubit teaching tool — beginner-readable, with
          textbook-rigor math underneath.
        - Every visualization is generated by the engine in
          `quantum_noise_lab` and covered by 211 automated tests.
        - The Validation Lab proves the simulator matches the analytical
          formulas for amplitude and phase damping of |+⟩.
        - Conventions (phase-damping form, fidelity definition, depolarizing
          parameterization) are pinned and documented.
        """
    )
with col_b:
    st.subheader("What this lab is *not*")
    st.markdown(
        """
        - Not a general-purpose quantum-computing simulator.
        - Not a multi-qubit framework — depth, not breadth.
        - Not a fault-tolerant quantum-error-correction implementation: the
          Protection Lab is a classical-style 3-repetition code for
          bit-flip errors only.
        - Not a hardware backend; results are conceptual, not predictions
          for any specific device.
        """
    )

st.divider()
st.caption(
    "Throughout the labs, the **Strength** slider is the probability or "
    "intensity of a noise event (γ, λ, p ∈ [0, 1]); 0 means no noise, 1 "
    "means the channel's strongest action."
)

page_footer()
