"use client";

import Link from "next/link";
import { motion } from "framer-motion";

import { GlassPanel } from "@/components/GlassPanel";
import { Logo } from "@/components/Logo";
import { MODULES } from "@/lib/modules";

export default function HomePage() {
  return (
    <div className="space-y-16">
      <section className="space-y-6 text-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.92 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, ease: [0.2, 0.8, 0.2, 1] }}
          className="flex justify-center"
        >
          <Logo size={88} />
        </motion.div>
        <motion.h1
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.55, delay: 0.1 }}
          className="font-serif text-4xl tracking-tight md:text-5xl"
        >
          Quantum Noise Learning Lab
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.55, delay: 0.18 }}
          className="mx-auto max-w-2xl text-balance text-base text-ink-dim md:text-lg"
        >
          An interactive single-qubit decoherence simulator. Density matrices, Kraus
          channels, fidelity, purity, eigenvalue analysis, side-by-side analytical
          validation, and a classical-style repetition-code intuition for why
          quantum error correction matters.
        </motion.p>
        <motion.blockquote
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.55, delay: 0.28 }}
          className="mx-auto max-w-3xl border-l-2 border-accent/60 pl-4 text-left font-serif text-base italic text-ink-dim md:text-lg"
        >
          “How does quantum information degrade under noise, and how can we
          understand, measure, visualize, and partially protect it?”
        </motion.blockquote>
      </section>

      <section className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-5">
        {MODULES.map((m, i) => (
          <motion.div
            key={m.slug}
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.42, delay: 0.05 * i + 0.34 }}
          >
            <Link href={m.href} className="group block h-full focus:outline-none">
              <GlassPanel className="flex h-full flex-col gap-3 p-5">
                <div className="flex items-baseline gap-2">
                  <span className="font-mono text-xs text-ink-dim">0{m.number}</span>
                  <h3 className="font-serif text-lg text-ink group-hover:text-accent">
                    {m.title}
                  </h3>
                </div>
                <p className="text-xs leading-relaxed text-ink-dim">{m.summary}</p>
                <span className="mt-auto text-xs font-medium text-accent">
                  Open →
                </span>
              </GlassPanel>
            </Link>
          </motion.div>
        ))}
      </section>

      <section className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <GlassPanel className="p-6">
          <h3 className="font-serif text-xl">What this lab is</h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-dim">
            <li>Focused single-qubit teaching tool — beginner-readable, textbook-rigor math underneath.</li>
            <li>Every visualization is generated by a TypeScript port of a 211-test Python reference engine; parity verified to 1e-12.</li>
            <li>Validation Lab proves the simulator matches the analytical formulas for amplitude and phase damping of |+⟩.</li>
            <li>Conventions (phase-damping form, fidelity definition, depolarizing parameterization) are pinned and documented.</li>
          </ul>
        </GlassPanel>
        <GlassPanel className="p-6">
          <h3 className="font-serif text-xl">What this lab is <em className="italic">not</em></h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-dim">
            <li>Not a general-purpose quantum-computing simulator.</li>
            <li>Not a multi-qubit framework — depth, not breadth.</li>
            <li>Not a fault-tolerant quantum-error-correction implementation: the Protection module is a classical-style 3-repetition code for bit-flip errors only.</li>
            <li>Not a hardware backend; results are conceptual, not predictions for any specific device.</li>
          </ul>
        </GlassPanel>
      </section>
    </div>
  );
}
